# Generated by Django 5.1.4 on 2025-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.AddField(
            model_name='tournament',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
