# Generated by Django 5.1.4 on 2025-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_remove_tournament_date_tournament_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date_time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
