# Generated by Django 5.1.4 on 2025-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_remove_tournament_date_time_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='required_team_size',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
