# Generated by Django 5.1.4 on 2025-03-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0008_alter_tournament_required_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='required_team_size',
            field=models.IntegerField(default={'Basketball': 5, 'Cricket': 11, 'Football': 11, 'Tennis': 2}, editable=False),
        ),
    ]
