# Generated by Django 5.1.4 on 2025-04-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0010_alter_tournament_required_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
