# Generated by Django 5.1.4 on 2025-03-10 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localsports', '0007_matchnotification_delete_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='players_needed',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='accepted_by',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='accepted_by',
            field=models.ManyToManyField(blank=True, related_name='joined_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
