# Generated by Django 5.1.4 on 2025-04-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Localsports', '0010_notification_delete_matchnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
